spring.application.name=backend
<<<<<<< HEAD
server.port=22933
spring.datasource.url=mysql-56b56f3-anurag-9df.b.aivencloud.com:22933/defaultdb?ssl-mode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=YOUR_PASSWORD
=======
server.port=4040
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/newtt
spring.datasource.username=root
spring.datasource.password=karthiksoul123#
>>>>>>> aaeec39a0066d358ed2415416b2bc90852ef2ed8

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true